# Generated by Django 2.2.7 on 2019-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to='\\None'),
        ),
    ]
