# Generated by Django 2.2.7 on 2019-11-14 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('fileSystem', '0002_auto_20191110_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload',
        ),
        migrations.AddField(
            model_name='file',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
